using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    private float axisH; // 左右のキーの値を格納
    Rigidbody2D rbody; // Rigidbody2Dの情報を扱うための媒体
    public float speed = 3.0f; // 歩くスピード

    // Start is called before the first frame update
    void Start()
    {
        // Playerに付いているRigidbody2Dコンポーネントを
        // 変数rbodyに格納
        rbody = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
    void Update()
    {
        // 引数Horizontalの場合、水平方向のキーが何か押された場合
        // 左なら-1、右なら1、その他なら0を格納
        axisH = Input.GetAxisRaw("Horizontal");
    }

    private void FixedUpdate()
    {
        // velocityに2軸の方向データを代入
        rbody.velocity = new Vector2(axisH * speed, rbody.velocity.y);
    }
}
